
name: CI

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - name: checkout the code
        uses: actions/checkout@v2

      - run: echo "Setting up JDK"
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Html Test Report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html
